### ISSUE TITLE
FYI: CloudBank compute credits for the Jupyter Security Training.

### ISSUE THREAD

**Issue by Carreau** [jupyter-governance/ec-team-compass#13]
Hello Executive Council, 

For your information, @rpwagner requested and obtain a small

The Jupyter security council have obtain an AWS account thanks to a [CloudBank award](https://www.cloudbank.org/). CloudBank is an NSF project that provides cloud resources for some NSF grants as part of their award. CloudBank also grants small awards for training and education, such as the upcoming workshops or Jupyter Security tutorials at JupyterCon.

@rpwagner is currently the only one with access and will used these compute cycle for the training at the [Zeek/Jupyter/trusted-ci security summit and training](https://www.trustedci.org/2023-cybersecurity-summit).

We do not expect all the could credits (~$2k) to be used, and want to let you know that this will be available for other use.

**Comment by Carreau** [comment]
cc @juanis2112 FYI

**Comment by rpwagner** [comment]
I recommend closing this because the CloudBank award has expired.
