### ISSUE TITLE
Updates to Meeting notes section

### ISSUE THREAD

**Issue by willingc** [jupyter-governance/ec-team-compass#18]
Is this the canonical place for meeting notes? Or is there another location?

If another location, we should probably link there. Alternatively, update here.

It may make sense to remove if time prevents it from being updated regularly.

**Comment by afshin** [comment]
Hi @willingc! Apologies for the super late response to this and the lacuna in minutes (that we are working on) but we've begun regularly posting, here is the place: https://executive-council-team-compass.readthedocs.io/en/latest/meeting_notes/

**Comment by afshin** [comment]
(So yes, that *is* the place, we just were woefully behind!)
