### ISSUE TITLE
Jupytercon.com renewal and squarespace. 

### ISSUE THREAD

**Issue by Carreau** [jupyter-governance/ec-team-compass#24]
I contacted the EC early november 2023 to indicate that the subscription for JupyterCon.com was about to expire/expired. I am again receiving those emails that the squarespace subscription is again about to expire. Was it renewed only for 3 month ? 

What should be done ? we have until Jan 29.

**Comment by fperez** [comment]
@Carreau - do you have the jupytercon.com domain yourself? If so, we should transfer it so it's in the same bundle of domains as all the others, that @afshin has nicely coalesced, so they can all be managed together.

**Comment by fperez** [comment]
Tagging #14 here as the relevant issue.

**Comment by Carreau** [comment]
No I don't think I own jupytercon.com, I'm also unsure how it is related to squarespace, and/org of the renewal is just the squarespace website or it it combines with the domain. 

This may be even more complicated as google domain is beeing absorbed by squarespace, so maybe Jupytercon.com was a google domain and is now a squarespace one ? 

I see Samina Trachier name from numfocus on the sqaurespace interface.

**Comment by Carreau** [comment]
website just expired. Closing.
