### ISSUE TITLE
Infinite redirect on ipython.nbviewer.org

### ISSUE THREAD

**Issue by Carreau** [jupyter-governance/ec-team-compass#26]
See https://github.com/ipython/ipython/issues/14415

I do not know how this is managed, I'm guessing the EC should have more informations.

**Comment by Carreau** [comment]
Can this be acknowledged ?

**Comment by Zsailer** [comment]
Hi @Carreau :wave:

I've added this to the agenda for our next meeting (next Tuesday). Apologies for not acknowledging this sooner—I appreciate you pinging us here as a reminder.

**Comment by Zsailer** [comment]
Hi @Carreau, I'm going to dive into this a bit deeper and see if I can figure it out. I got access the necessary accounts now, so I'll see what I can find. I'll keep things updated here.

**Comment by Carreau** [comment]
Thanks.

**Comment by Zsailer** [comment]
Hi @Carreau, I haven't forgotten about this! 😅 I'll respond on the original issue—having trouble reproducing on my end.

**Comment by Carreau** [comment]
oh, i ended up spending a few hours to fix it. if it works on your end then the new dns have propagated.

**Comment by Zsailer** [comment]
oh great! Thank you @Carreau for taking the time here. I really appreciate it!

**Comment by Carreau** [comment]
No worries, but in general it would be good to have a plan on who is responsible for that kind of things.
