### ISSUE TITLE
Can a triage team be created on the enterprise level?

### ISSUE THREAD

**Issue by krassowski** [jupyter-governance/ec-team-compass#31]
We often find it annoying on triage meetings that only some of us can add/remove labels in Notebook or repo or in JupyterLab repo or in nbclassic repo or in JupyterLab Desktop repo (which is about the breadth to which the triage team gets, see https://github.com/jupyterlab/frontends-team-compass/issues/228)

In context of https://github.com/jupyter/governance/issues/219 can the triage team be created on Enterprise level and triage rights granted to everyone who regularly attends the triage calls to reduce the friction?

CC @RRosio @JasonWeill

**Comment by jasongrout** [comment]
As far as I can tell, we cannot create teams at the enterprise level. Teams and roles seem to be an org-level concept.

**Comment by jasongrout** [comment]
That said, should we create a Jupyter Frontends Triage team in the github.com/jupyter org?

**Comment by jasongrout** [comment]
Mike, I created a jupyter frontends triage team and added you, and added triage permissions on the notebook repo. 

https://github.com/orgs/jupyter/teams/jupyter-frontends-triage/members

Who else should be added?

**Comment by krassowski** [comment]
Jason W and Rosio (see above for GitHub handles)

**Comment by jasongrout** [comment]
Done!
