### ISSUE TITLE
Request to move all repos from jupyter-incubator into jupyter ? 

### ISSUE THREAD

**Issue by Carreau** [jupyter-governance/ec-team-compass#51]
There are 4 repos:
  - Spark magic (last activity 6 month ago), move to jupyter as is
  - proposals, contentmanagement, declarativewidgets_explorer (last activity 4+ years ago, and archived) move to Jupyter as well. 

Then archive the org and kick everybody out.

**Comment by fperez** [comment]
Thanks @Carreau! We've put it on the backlog for our tracking board so we don't lose track.

But the actual decision should be made by the SSC - we'd appreciate input from this team! (we're looking for a convenient way to just tag the SSC here, ideas welcome!).

**Comment by jasongrout** [comment]
FYI, here's the reference for SSC [owning the incubation process](https://jupyter.org/governance/software_steering_council.html#sole-responsibilities).

**Comment by Carreau** [comment]
> But the actual decision should be made by the SSC - we'd appreciate input from this team! (we're looking for a convenient way to just tag the SSC here, ideas welcome!).

I don't have enough permission, but I think one should create an SSC team (possibly replicate it on all organisations SIC). And ask review from the teams/ members of the teams.

**Comment by jasongrout** [comment]
FYI, I emailed the SSC and asked them to respond, and asked if there were a better place to carry out this discussion that is more under the SSC purview.

**Comment by jtpio** [comment]
Maybe opening an issue on https://github.com/jupyter/software-steering-council-team-compass so we can ping the SSC team, and ask if everyone is ok to move these 4 repos to the `jupyter` org?

**Comment by jasongrout** [comment]
@jtpio: awesome, perfect. 

@Carreau - can you open this issue in the [SSC team compass](https://github.com/jupyter/software-steering-council-team-compass)?

**Comment by Carreau** [comment]
Done.

**Comment by jasongrout** [comment]
Great. I'll close this issue here. Thanks Matthias.
