### ISSUE TITLE
Migrate Jupyter meetings to LF Zoom account

### ISSUE THREAD

**Issue by jasongrout** [jupyter-governance/ec-team-compass#66]
We need to migrate our zoom meetings off of our NumFOCUS zoom account. We can use zoom through Linux Foundation.

# Current proposal

Some options for meeting zoom channels:

1. (**Recommended**) Have a shared zoom meeting channel for the project. It looks like all of our meetings that use zoom are scheduled between 7am-5pm PT, so we could create a 10-hour zoom meeting each day during that slot that we can use as a shared channel. If we have meetings outside of this time slot, we could create two more channels to cover the 24-hour day.
    - (+) A shared channel can promote community, in that there are serendipitous meetings between people coming and going using the shared channel. Sometimes people from an earlier meeting will stay around for later meetings, etc.
    - (+) Simple for the community to transition, very similar to our existing single zoom room. We just change one zoom link to another zoom link.
    - (-) There can be resource contention if two groups would like to meet at the same time, or if an earlier meeting runs long. (We can use breakout rooms or a secondary channel if resource contention becomes an issue).
2. Create separate LF zoom meetings for each Jupyter meeting.
    - (-) Could be harder to schedule since we have a bottleneck of about 3 people who can schedule and manage meetings, but perhaps this isn't so bad once recurring meetings are set up?
    - (+) Each Jupyter meeting gets its own dedicated space, recordings, etc. No resource contention.
    - (+) Fits how calendar zoom meetings usually work - a different zoom for each meeting.
    - (+) Fits how LF intends its meeting system to be used.

**Recommendation**: I propose we go with option 1, a shared zoom channel hosted by LF, which I think is the smoothest transition from our current system. (Note that these two options are not mutually exclusive; we can have the shared channel, and if some group wants a separate meeting, we can set one up.)

FYI, some constraints of the Linux Foundation (LF) zoom system:

1. LF will not create a single perpetually open zoom channel like we have now.
2. LF discourages us from distributing raw zoom links that bypass their signin process, but I am willing to do so to not create a disruption in the community.
3. A LF zoom meeting can last for up to 10 hours and the most frequent repetition is daily.
4. It seems that if you try to connect to a meeting during a time it is not scheduled, zoom kicks you out after about 5 minutes.
5. We only have 3 admins, i.e., people that can set up meetings. LF typically recommends having just 2-3 admins per project. The permissions are coarse, so it's not possible to just make some set of people only in charge of scheduling meetings.

What do you think?

**Comment by jasongrout** [comment]
We experimented in the last EC meeting with using the LF Zoom. One thing we tried was making several recordings during the meeting. All 4 of our zoom recordings showed up in the LF project management site (and there is an option in LF to make the recordings show up for individuals that attended in their LF individual dashboard as well). Basically, PCC linked to the zoom page for the recordings, which it seems uses an unlisted URL for its security rather than true authentication. I could download the transcript file, the audio file, and the video files for the recordings. Unfortunately, it seemed that the video was 640x360, so rather low resolution. I'll ask about that.

**Comment by Ruv7** [comment]
@jasongrout  owns next step which is to write a message we can send to the wider Jupyter community.

**Comment by jasongrout** [comment]
Some updates:

1. LF will not create a single perpetually open zoom channel, and discourages us from bypassing their lfx signin process.
2. We can schedule meetings for at most 10 hours, and the most frequent repitition is daily.
3. It seems that if you try to connect to a meeting after it is scheduled, it kicks you out after 5 minutes.
4. We only have 3 LFX admins, i.e., people that can set up meetings. They typically only have a few per project. The LFX permissions are not very fine-grained, so it's not possible to just make some set of people only in charge of scheduling meetings.

Some options for meetings:

1. Have a shared meeting channel for the project. Since we can only schedule at most 10-hour meetings daily, we'd actually have 3 zoom channels to fully cover each day.
    - (+) A shared channel can promote community, in that there are serendipitous meetings between people coming and going using the shared channel. Sometimes people from an earlier meeting will stay around for later meetings, etc.
    - (+) Simple for the community to transition, very similar to our existing single zoom room.
    - (-) There can be resource contention if two groups would like to meet at the same time, or if an earlier meeting runs long. (We can use breakout rooms or a secondary channel if resource contention becomes an issue).
2. Create separate LFX zoom meetings for each Jupyter meeting.
    - (-) Could be harder to schedule since we have a bottleneck of people who can schedule meetings, but perhaps not so bad?
    - (+) Each Jupyter meeting gets its own dedicated space, recordings, etc. No resource contention.
    - (+) Fits how calendar zoom meetings usually work - a different zoom for each meeting.

**Comment by fperez** [comment]
Thanks @jasongrout for doing all this. I find the extra authentication layer extremely annoying, but so be it. Not a hill I have time to die on.

**Comment by jasongrout** [comment]
> Thanks @jasongrout for doing all this. I find the extra authentication layer extremely annoying, but so be it. Not a hill I have time to die on.

FYI, we don't have to have the extra auth layer if we just distribute the zoom links themselves.

**Comment by jasongrout** [comment]
Of course, the two options above are not mutually exclusive - we could have the shared channel, and if someone wants a different recurring zoom meeting, it's easy to set up.

**Comment by jasongrout** [comment]
We've had a few days for the SSC to weigh in and for the SSC to have a weekly meeting (thanks to those who did weigh in with reactions on the original post). I'll go ahead with option 1, creating a zoom meeting that spans the times we usually use for meetings, which can be a drop-in replacement for our numfocus meeting, and I'll distribute that zoom link to the EC and SSC. If people want more meetings, please contact me and I'm happy to set up separate zoom meetings as requested.

**Comment by jasongrout** [comment]
Here is the info for a public Jupyter Zoom channel, active from 1200-2200 UTC daily (5am-3pm PT), which can be used to replace the current Jovyan jupyter channel provided by NumFOCUS. Please let me know if you want to create more zoom meetings for Jupyter business.

Jupyter Zoom Channel 1200-2200 UTC (0500-1500 PT)

https://zoom.us/j/95228013874?pwd=Ep7HIk8t9JP6VToxt1Wj4P7K5PshC0.1

Meeting ID: 95228013874
Meeting Passcode: 659973

One tap mobile:
US (iOS): +12532158782,,95228013874#,,,,*659973# or +13462487799,,95228013874#,,,,*659973#
US (Android): +12532158782;95228013874#;659973# or
+13462487799;95228013874#;659973#
Or dial:
US: +1 253 215 8782 or +1 346 248 7799 or +1 669 900 6833 or +1 301 715 8592
or +1 312 626 6799 or +1 646 374 8656 or 877 369 0926 (Toll Free) or 855 880 1246 (Toll Free)
Canada: +1 647 374 4685 or +1 647 558 0588 or +1 778 907 2071 or +1 204 272 7920
or +1 438 809 7799 or +1 587 328 1099 or 855 703 8985 (Toll Free)
International numbers: https://zoom.us/u/alwnPIaVT

**Comment by jasongrout** [comment]
Let's plan to migrate off of the NumFOCUS zoom by the end of 2024, so we can delete the NumFOCUS zoom meeting Jan 1 2025.

**Comment by jtpio** [comment]
Thanks all for working on this and the updates.

> One thing we tried was making several recordings during the meeting. All 4 of our zoom recordings showed up in the LF project management site (and there is an option in LF to make the recordings show up for individuals that attended in their LF individual dashboard as well). Basically, PCC linked to the zoom page for the recordings, which it seems uses an unlisted URL for its security rather than true authentication. I could download the transcript file, the audio file, and the video files for the recordings.

About the recordings, will it still be possible for subproject council members to download the recordings, so they can be uploaded to the YouTube channel?

Typically for the Jupyter Frontends, every week, we connect to the https://zoom.us website with the credentials stored in 1password to download the recordings from there. That allows us to upload the video to YouTube shortly after the meeting has ended, so it's quickly available to those who were not able to join.

Will we still be able to do this after the switch?

**Comment by jasongrout** [comment]
> Will we still be able to do this after the switch?

Great question. If an attendee claims the host role (using the host key that is available in 1password), they can turn on/off the cloud recording in zoom.

I can access recordings in the LF tool I use to create the meeting, which brings me to a zoom web page where I can download the recording. Let's try this:

1. Create an [LFX account](https://lfx.linuxfoundation.org/) for whoever wants to manage this recording (click "Create" in the upper right)
2. I'll add that person to the shared channel meeting invite (I just need to know the email address of the account that was created). They may be able to access the recording then.

**Comment by jtpio** [comment]
Thanks @jasongrout!

I just created an account (with my personal gmail address), and there seems to be a page for meetings indeed: https://openprofile.dev/my-meetings.

Let me know when you have added me, and I can double check I can download the recording.

**Comment by jasongrout** [comment]
Okay, I added you to the meeting. What can you see? Is there a place that indicates there are no recordings yet?

**Comment by jtpio** [comment]
> _Edit: do you want to take this quick back and forth to zulip, then we can summarize our findings back here?_

Sounds good :+1:

**Comment by jasongrout** [comment]
Some findings:

1. Zoom recordings don't seem to be available until after a meeting ends. For the shared channel, that means after 2200UTC. That means the latency is more like 1 day rather than 1 hour.
2. The zoom video is 360p unless you screen share, in which case it is the resolution of the screen.
3. Each recording on the channel is separate, with its own transcript, chat transcript, audio, and video downloads. If there is no transcript or chat, those files do not appear.
4. It seems that if the meeting has recordings unchecked in the settings, I can't see the recording in PCC. However, individuals can still see the recordings in their individual dashboard.
5. Jeremy created a new LFX account, and I added his email to a meeting. In his individual dashboard, he ended up seeing a *lot* of Jupyter meetings, though. How did it know to add him to all these extra meetings, where he isn't an attendee? Were these the "public" meetings (in which case, do they show up for *every* lfx user?

**Comment by jasongrout** [comment]
We thought we'd do another test recording to verify that we could get recordings off of the shared channel, then we'd be set to do a test run of the frontends meeting in a week, then officially move over Jan 1.

**Comment by jasongrout** [comment]
@jtpio, LFX support just got back to me. They are submitting a feature request to allow access to any recordings that were manually started during a meeting, and in the meantime, they said we could contact support and they would get us a link to the recording. For now, does that work for us?

To put in a support request, click the question mark in the LFX tool in the upper right:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/a2ade6b1-193e-4979-a2fb-056b0171996b" />

I've found LFX support to be extremely responsive.

**Comment by jasongrout** [comment]
Following up on this: NumFOCUS will be shutting down their Jupyter zoom channel Jan 17, one week from today.

Again, we've created a long-running zoom meeting each day that you can swap in for the NumFOCUS channel. See the connection information above at https://github.com/jupyter-governance/ec-team-compass/issues/66#issuecomment-2529265199

Basically, the swap would be changing this URL:

https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09

to this URL:

https://zoom.us/j/95228013874?pwd=Ep7HIk8t9JP6VToxt1Wj4P7K5PshC0.1

If you would like a separate zoom created for your meeting, please let me know and we can also do that.
